Public Class Parametrizaciones
    Public tablas() As String = {"AYUIDA", "BITACORA", "DISPOSITIVO", "DV", "FAMILIA", "FAMPAT", "IDIOMA", "MENSAJEIDIOMA", "MENSAJEAYUDA", "PATENTE", "SOPORTE", "TIPO_DISPOSITIVO", "TIPO_MONITOREO", "USUARIO", "USUFAM", "USUPAT"}
    Public tablasDV() As String = {"BITACORA", "DISPOSITIVO", "FAMILIA", "FAMPAT", "PATENTE", "SOPORTE", "TIPO_DISPOSITIVO", "TIPO_MONITOREO", "USUARIO", "USUFAM", "USUPAT"}





End Class

